package ec3.dummycore.core;

import DummyCore.Core.Core;
import DummyCore.Utils.*;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.*;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import cpw.mods.fml.relauncher.Side;
import net.minecraft.command.CommandHandler;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.common.MinecraftForge;

import java.lang.reflect.Method;
import java.util.Arrays;

@Mod(
    modid = "DummyCore",
    name = "DummyCore",
    version = "1.13",
    useMetadata = false
)
public class CoreInitializer {
    public static final String modid = "DummyCore";
    public static final String modname = "DummyCore";
    public static final String version = "1.13";
    public static ec3.dummycore.core.CoreInitializer instance;
    public static DummyConfig cfg = new DummyConfig();
    public static SimpleNetworkWrapper network;
    @SidedProxy(
        clientSide = "DummyCore.Utils.NetProxy_Client",
        serverSide = "DummyCore.Utils.NetProxy_Server"
    )
    public static NetProxy_Server proxy;
    public static final DummyPacketHandler packetHandler = new DummyPacketHandler();

    public CoreInitializer() {
    }

    public static ModMetadata initMetadata() {
        ModMetadata meta = new ModMetadata();
        meta.autogenerated = false;
        meta.modId = "DummyCore";
        meta.name = "DummyCore";
        meta.version = "1.13";
        meta.credits = "Modbder";
        meta.authorList = Arrays.asList("Dummy Thinking Team; Modbder; TheDen2099");
        meta.description = "Dummy Core is a required package to launch mods made by Dummy Thinking team.";
        return meta;
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        ModMetadata meta = e.getModMetadata();
        meta.autogenerated = false;
        meta.modId = "DummyCore";
        meta.name = "DummyCore";
        meta.version = "1.13";
        meta.credits = "Modbder";
        meta.authorList = Arrays.asList("Dummy Thinking Team; Modbder; TheDen2099");
        meta.description = "Dummy Core is a required package to launch mods made by Dummy Thinking team.";
        if (instance == null) {
            instance = this;
        }

        network = NetworkRegistry.INSTANCE.newSimpleChannel("DummyCore");
        network.registerMessage(DummyPacketHandler.class, DummyPacketIMSG.class, 0, Side.SERVER);
        network.registerMessage(DummyPacketHandler.class, DummyPacketIMSG.class, 0, Side.CLIENT);
        network.registerMessage(DummyTilePacketHandler.class, DummyPacketIMSG_Tile.class, 1, Side.SERVER);
        network.registerMessage(DummyTilePacketHandler.class, DummyPacketIMSG_Tile.class, 1, Side.CLIENT);

        try {
            Core.registerModAbsolute(this.getClass(), "DummyCore", e.getModConfigurationDirectory().getAbsolutePath(), cfg);
        } catch (Exception var7) {
            System.out.println("Oh, come on Forge. If something has got wrong here - this is it.");
            System.out.println("No, reriously, if an exception is bbeing thrown here - nothing is going to load");
            System.out.println("Like, even the gam itself, since an exception here means File System error.");
            System.out.println("And a file system error here -> impossible to create literally any file in directory!");
            System.out.println("But when I'm trying to set a System.exit(-1) here - oww, not allowed?");
            System.out.println("Fine, I can work without it... Reflection time!");

            try {
                Class<System> system = System.class;
                Method exit = system.getMethod("exit", Integer.TYPE);
                exit.invoke((Object)null, -1);
            } catch (Exception exc) {
                exc.printStackTrace();
                return;
            }
        }

        MinecraftForge.EVENT_BUS.register(new DummyEventHandler());
        MinecraftForge.EVENT_BUS.register(new DummyDataUtils());
        FMLCommonHandler.instance().bus().register(new DummyEventHandler());
        proxy.registerInfo();
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent e) {
        NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
        proxy.registerInit();
    }

    /** @deprecated */
    @Deprecated
    @Mod.EventHandler
    public void onServerStart(FMLServerAboutToStartEvent e) {
    }

    @Mod.EventHandler
    public void onServerStop(FMLServerStoppedEvent e) {
        DummyDataUtils.stop();
    }

    @Mod.EventHandler
    public void serverStart(FMLServerStartingEvent event) {
        MinecraftServer mcserver = event.getServer();
        ((CommandHandler)mcserver.getCommandManager()).registerCommand(new CommandTransfer());
    }
}
